<script>
  import Alert from './view/Alert.svelte';
  import Config from './view/Config.svelte';
  import Search from './view/Search.svelte';
  import Nav from './view/Nav.svelte';
  import { google_drive } from './inc/google-drive.js';
  import {
    CONFIG_SYNC_SAVE_STATE,
    configSyncSaveState,
    configSyncMessageShow,
    configSyncMessageType,
    configSyncMessage
  } from './store/config-stores.js';

  // Super cheap hash routing
  let hash = document.location.hash;
  function updateHash() {
    hash = document.location.hash;
  }
  window.onhashchange = updateHash;
</script>

<div class="container">
  {#if hash === '#config'}
    <Nav {hash} />
    <main>
      <Config />
    </main>
  {:else}
    <main>
      <Search />
    </main>
    <Nav {hash} />
  {/if}

  {#if $configSyncMessageShow}
    <Alert type={$configSyncMessageType} message={$configSyncMessage} />
  {/if}
</div>

<svelte:head>
  <script
    async
    defer
    src="https://apis.google.com/js/api.js"
    on:load={google_drive.onLoad}
    onreadystatechange="if (this.readyState === 'complete') this.onload()"></script>

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "SoftwareApplication",
        "name": "Quixer",
        "url": "https://quixer.onl/",
        "author": {
          "@type": "Person",
          "name": "Chris Putnam"
        },
        "datePublished": CURRENT_DATE_STAMP,
        "applicationCategory": "Productivity"
      }
  </script>
</svelte:head>

<style>
  .container {
    height: 100%;
    display: flex;
    flex-wrap: wrap;
    align-content: space-between;
    justify-content: center;
    align-items: flex-start;
  }
</style>
